[project]
name = "mnp-liver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib==3.10.3",
    "numpy==1.23.1",
    "pandas==2.2.3",
    "scikit_learn==1.6.1",
    "seaborn==0.13.2",
    "umap==0.1.1"
]
